MSG (Eunexpected_eof,
     _T("予期しないEOFを検出しました")),
MSG (Eunterminated_comment,
     _T("コメントが終了していません")),
MSG (Eno_chars_following_single_escape,
     _T("‘\\’の後ろに文字がありません")),
MSG (Eunterminated_string,
     _T("文字列が終了していません")),
MSG (Eincomplete_dispatch_macro,
     _T("ディスパッチングマクロ定義が不完全です")),
MSG (Eillegal_character,
     _T("不正な文字です")),
MSG (Eunsupported_dispatch_macro,
     _T("未サポートのディスパッチングマクロです")),
MSG (Eundefined_dispatch_macro,
     _T("未定義のディスパッチングマクロです")),
MSG (Eno_following_hex_digits,
     _T("‘\\x’の後に16進文字がありません")),
MSG (Einvalid_dotted_list,
     _T("不正なドットリストです")),
MSG (Eunexpected_char,
     _T("予期しない文字です")),
MSG (Eunknown_char_name,
     _T("不正な文字名です")),
MSG (Echar_code_out_of_range,
     _T("文字コードが範囲外です")),
MSG (Einvalid_char_code_syntax,
     _T("不正な文字表記です")),
MSG (Eno_initializer_for_vector,
     _T("ベクタの初期化オブジェクトがありません")),
MSG (Etoo_many_initializer_for_vector,
     _T("ベクタの初期化オブジェクトが多すぎます")),
MSG (Elabel_number_redefined,
     _T("ラベルが再定義されました")),
MSG (Eundefined_label,
     _T("ラベルが定義されていません")),
MSG (Edot_only_token,
     _T("ドットのみのトークンです")),
MSG (Eno_label_for_number_equal,
     _T("‘#=’にラベルが指定されていません")),
MSG (Eno_label_for_number_number,
     _T("‘##’にラベルが指定されていません")),
MSG (Einvalid_midfix_parameter,
     _T("不正な間置引数が指定されました")),
MSG (Enumber_R_parameter_out_of_range,
     _T("‘#R’の引数は2から36です")),
MSG (Ewrong_argument_for_number_plus,
     _T("‘#+’の条件が不正です")),
MSG (Ewrong_argument_for_number_minus,
     _T("‘#-’の条件が不正です")),
MSG (Ewrong_integer_format,
     _T("不正な整数のフォーマットです")),
MSG (Ebad_package_marker,
     _T("不正なパッケージマーカです")),
MSG (Epackage_marker_appears_end_of_token,
     _T("パッケージマーカがトークンの終わりにあります")),
MSG (Etwo_package_marker_appears_beginning_of_token,
     _T("2つのパッケージマーカがトークンの先頭にあります")),
MSG (Eexternal_symbol_not_found,
     _T("外部シンボルは見つかりません")),
MSG (Ecomma_atsign_after_backquote,
     _T("‘`’の後に‘,@’があります")),
MSG (Ecomma_dot_after_backquote,
     _T("‘`’の後に‘,.’があります")),
MSG (Emalformed_comma,
     _T("不正な‘,’です")),
MSG (Edotted_comma_atsign,
     _T("‘,@’がドットリストにあらわれました")),
MSG (Edotted_comma_dot,
     _T("‘,.’がドットリストにあらわれました")),
MSG (Edivision_by_zero,
     _T("0で除算しました")),
MSG (Eunbound_variable,
     _T("変数が定義されていません")),
MSG (Eundefined_function,
     _T("関数が定義されていません")),
MSG (Emodify_constant,
     _T("定数は変更できません")),
MSG (Einvalid_keyword_list,
     _T("不正なキーワードリストです")),
MSG (Einvalid_lambda_list,
     _T("不正なラムダリストです")),
MSG (Einvalid_function,
     _T("不正な関数です")),
MSG (Einvalid_variable_list,
     _T("不正な変数リストです")),
MSG (Ebad_macro_form,
     _T("不正なマクロフォームです")),
MSG (Einvalid_argument,
     _T("引数が不正です")),
MSG (Etype_error,
     _T("不正なデータ型です")),
MSG (Ebad_type_specifier,
     _T("型指定子が不正です")),
MSG (Erange_error,
     _T("範囲外の値です")),
MSG (Etoo_few_arguments,
     _T("引数が少なすぎます")),
MSG (Etoo_many_arguments,
     _T("引数が多すぎます")),
MSG (Estorage_condition,
     _T("メモリ不足です")),
MSG (Estack_overflow,
     _T("スタックオーバーフロー")),
MSG (Eformat_argument_exhausted,
     _T("引数が足りません")),
MSG (Eend_of_ctl_string,
     _T("制御文字列が途中で終わっています")),
MSG (Eargument_is_circle,
     _T("引数が循環しています")),
MSG (Etoo_many_parameters,
     _T("パラメータが多すぎます")),
MSG (Efmt_r_requires_2_36,
     _T("基数は2から36です")),
MSG (Esign_following_no_chars,
     _T("符号の後に文字がありません")),
MSG (Esign_following_not_digits,
     _T("符号の後に数字がありません")),
MSG (Equote_following_no_chars,
     _T("‘'’の後に文字がありません")),
MSG (Ecannot_backup,
     _T("引数をバックアップできません")),
MSG (Ecannot_goto,
     _T("引数の位置指定が範囲外です")),
MSG (Eillegal_colon,
     _T("不正な‘:’です")),
MSG (Eillegal_atsign,
     _T("不正な‘@’です")),
MSG (Eillegal_colon_atsign,
     _T("不正な‘:@’です")),
MSG (Eillegal_parameter_type,
     _T("パラメータの型が不正です")),
MSG (Eparameter_out_of_range,
     _T("パラメータの値が範囲外です")),
MSG (Eillegal_fmt_V_parameter,
     _T("Vパラメータの型が不正です")),
MSG (Eclose_paren_expected,
     _T("‘)’が見つかりません")),
MSG (Eclose_brace_expected,
     _T("‘}’が見つかりません")),
MSG (Eclose_bracket_expected,
     _T("‘]’が見つかりません")),
MSG (Egreater_than_expected,
     _T("‘>’が見つかりません")),
MSG (Etoo_many_conditional_form,
     _T("条件節が多すぎます")),
MSG (Eillegal_colon_circumflex,
     _T("不正な‘~:^’です")),
MSG (Eillegal_format_directive,
     _T("不正なformat指示子です")),
MSG (Ejustification_not_implemented,
     _T("justificationは実装されていません")),
MSG (Elists_length_different,
     _T("リストの長さが異なります")),
MSG (Etest_and_test_not_are_both_specified,
     _T("‘:test’と‘:test-not’が両方指定されています")),
MSG (Eis_special_variable,
     _T("スペシャル変数は定数にできません")),
MSG (Eis_constant_variable,
     _T("定数はスペシャル変数にできません")),
MSG (Evector_has_no_fill_pointer,
     _T("フィルポインタを持たないベクタです")),
MSG (Efill_pointer_is_zero,
     _T("フィルポインタが0です")),
MSG (Eelement_and_contents_are_both_specified,
     _T("‘:initial-element’と‘:initial-contents’が両方指定されています")),
MSG (Einitial_contents_has_wrong_length,
     _T("‘:initial-contents’の長さが指定された長さと一致しません")),
MSG (Epath_name_too_long,
     _T("パス名が長すぎます")),
MSG (Einvalid_if_does_not_exist_option,
     _T("不正な‘:if-does-not-exist’オプションです")),
MSG (Einvalid_if_exists_option,
     _T("不正な‘:if-exists’オプションです")),
MSG (Einvalid_direction_option,
     _T("不正な‘:direction’オプションです")),
MSG (Ecannot_create_file,
     _T("ファイルをオープンできません")),
MSG (Elabel_reference_self,
     _T("ラベル付けされたオブジェクト自身を参照しています")),
MSG (Epackage_already_exists,
     _T("同じ名前のパッケージが存在します")),
MSG (Epackage_value_is_not_package,
     _T("*package*の値がパッケージではありません")),
MSG (Eno_package,
     _T("パッケージが存在しません")),
MSG (Ecannot_use_keyword_package,
     _T("keywordパッケージはuseできません")),
MSG (Epackage_is_used,
     _T("パッケージは他のパッケージに使用されています")),
MSG (Eunable_to_unintern_shadowing_symbol,
     _T("シャドウイングシンボルはuninternできません")),
MSG (Eis_not_accessible_symbol,
     _T("アクセスできないシンボルです")),
MSG (Ecannot_export_because_name_conflict,
     _T("名前が衝突するためexportできません")),
MSG (Eunable_to_unexport_keyword_package,
     _T("keywordパッケージからunexportできません")),
MSG (Ecannot_import_because_name_conflict,
     _T("名前が衝突するためimportできません")),
MSG (Ecannot_use_because_name_conflict,
     _T("名前が衝突するためuseできません")),
MSG (Ecannot_access_symbol_from_home_package,
     _T("ホームパッケージからアクセスできません")),
MSG (Efile_not_found,
     _T("ファイルが見つかりません")),
MSG (Earithmetic_domain_error,
     _T("0の対数は未定義です")),
MSG (Efloating_point_overflow,
     _T("オーバーフローしました")),
MSG (Efloating_point_underflow,
     _T("アンダーフローしました")),
MSG (Ecannot_coerce_to,
     _T("型変換できません")),
MSG (Eundefined_struct,
     _T("未定義の構造体です")),
MSG (Einvalid_struct_syntax,
     _T("不正な構造体の構文です")),
MSG (Einvalid_slot_name,
     _T("不正なスロット名です")),
MSG (Erandom_state_is_not_random_state,
     _T("*random-state*の値がランダムステート型ではありません")),
MSG (Einvalid_random_state_initializer,
     _T("ランダムステートの初期化オブジェクトが不正です")),
MSG (Eread_only_buffer,
     _T("書込み禁止バッファです")),
MSG (Eis_character_special_file,
     _T("デバイスファイルです")),
MSG (Eundo_outside_region,
     _T("変更した場所が見えないのでアンドゥでけん")),
MSG (Eundo_information_not_kept,
     _T("このバッファはアンドゥの記録をしていません")),
MSG (Eno_undo_information,
     _T("これ以上アンドゥできません")),
MSG (Ecannot_redo_more,
     _T("これ以上リドゥできません")),
MSG (Edeleted_buffer,
     _T("削除されたバッファです")),
MSG (Equit,
     _T("Quit")),
MSG (Ekey_not_bound,
     _T("Key not bound")),
MSG (Mgarbage_collecting,
     _T("Garbage collecting...")),
MSG (Mgarbage_collecting_done,
     _T("Garbage collecting...done")),
MSG (Eno_mark_set_in_this_window,
     _T("マークが設定されていません")),
MSG (Ebad_interactive_specifier,
     _T("不正なinteractive指定子です")),
MSG (Enot_a_command,
     _T("不正なコマンドです")),
MSG (Eno_such_buffer,
     _T("バッファが見つかりません")),
MSG (Edeleted_window,
     _T("削除されたウィンドウです")),
MSG (Ecannot_split,
     _T("分割できません")),
MSG (Ecannot_split_minibuffer_window,
     _T("ミニバッファウィンドウは分割できません")),
MSG (Eonly_one_window,
     _T("カレントウィンドウは削除できません")),
MSG (Edeleted_marker,
     _T("削除されたマーカです")),
MSG (Emarker_on_different_buffer,
     _T("他のバッファのマーカです")),
MSG (Emarker_is_not_set,
     _T("マーカはセットされていません")),
MSG (Ecannot_change_window_size,
     _T("変更できません")),
MSG (Eattempt_to_use_minibuffer_recursively,
     _T("ミニバッファは再帰的に使用できません")),
MSG (Esilent_quit,
     _T("")),
MSG (Eempty_buffer_names_not_allowed,
     _T("バッファ名が空文字列です")),
MSG (Ebuffer_name_too_long,
     _T("バッファ名が長すきます")),
MSG (Ecannot_switch_in_minibuffer_window,
     _T("ミニバッファウィンドウではバッファの変更はできません")),
MSG (Eis_a_directory,
     _T("指定されたパスはディレクトリです")),
MSG (Ecannot_specify_shift_bit,
     _T("SHIFTは指定できません")),
MSG (Ecannot_delete_backup_file,
     _T("すでに存在するバックアップファイルの削除ができません")),
MSG (Mcannot_create_numbered_backup_file,
     _T("番号付きバックアップファイルが作成できません")),
MSG (Mbuffer_needs_not_save,
     _T("保存する必要はありません")),
MSG (Mbuffer_is_truncated,
     _T("このバッファは中途半端にファイルを読み込んでいます。\n")
     _T("このまま保存するとファイルの後半が失われる可能性があります。\n")
     _T("保存しますか?")),
MSG (Eno_file_name,
     _T("ファイル名がありません")),
MSG (Eis_write_protected,
     _T("書込み禁止ファイルです")),
MSG (Mdisk_file_has_changed,
     _T("知らない間にファイルの日付が変わっています。保存しますか?")),
MSG (Ecannot_make_temp_file_name,
     _T("一時ファイルが作成できません")),
MSG (Mwriting,
     _T("保存中...")),
MSG (Ecannot_create_backup_file,
     _T("バックアップファイルが作成できません")),
MSG (Mauto_saving,
     _T("自動セーブ中...ちょっと待ってね")),
MSG (Mauto_saving_done,
     _T("自動セーブ終わり")),
MSG (Ewrite_error,
     _T("書き込みエラー")),
MSG (MFwrote_n_lines,
     _T("%d行")),
MSG (Ere_invalid_pattern,
     _T("不正なパターンです")),
MSG (Ere_unmatched_lbrace,
     _T("‘\\{’に対応する‘\\}’がありません")),
MSG (Ere_malformed_repeat_count,
     _T("‘\\{M,N\\}’のフォーマットが不正です")),
MSG (Ere_nesting_too_deep,
     _T("グルーピングのネストが深すぎます")),
MSG (Ere_unmatched_rparen,
     _T("‘\\)’に対応する‘\\(’がありません")),
MSG (Ere_unmatched_lparen,
     _T("‘\\(’に対応する‘\\)’がありません")),
MSG (Eunmatched_bracket,
     _T("‘[’に対応する‘]’がありません")),
MSG (Einvalid_syntax_spec,
     _T("不正なシンタックス指定子です")),
MSG (Einvalid_integer_format,
     _T("不正な数値の形式です")),
MSG (Enot_a_directory,
     _T("指定されたパスはディレクトリではありません")),
MSG (Munbalanced_parenthesis,
     _T("対応する括弧が見つかりません")),
MSG (Munmatched_parenthesis,
     _T("一致する括弧が見つかりません")),
MSG (Econtaining_expression_ends_prematurely,
     _T("式が中途半端に終了しています")),
MSG (Munbalanced_else,
     _T("‘else’に対応する‘if’がありません")),
MSG (Melse_not_within_a_conditional,
     _T("‘else’が妙な場所にあります")),
MSG (Ecreate_thread_failed,
     _T("スレッドが作成できません")),
MSG (Msubprocesses_are_running,
     _T("サブプロセスが走っています。こいつらを死なして終了しますか?")),
MSG (Esubprocess_is_already_running,
     _T("すでにサブプロセスが走っているため実行できません")),
MSG (Ebuffer_has_subprocess,
     _T("サブプロセスが走っています。")),
MSG (Mfile_has_changed_on_disk,
     _T("知らない間にファイルの日付が変わっています。\n編集を継続しますか?")),
MSG (Eedit_canceled,
     _T("キャンセルされました")),
MSG (Mmodified_buffers_exist,
     _T("%d個のバッファが変更されています。セーブしないで終了しますか?")),
MSG (Euninitialized_menu_item,
     _T("初期化されていないメニューです")),
MSG (Eis_not_popup_menu,
     _T("ポップアップメニューではありません")),
MSG (Etoo_many_menu_items,
     _T("メニュー項目が多すぎます")),
MSG (Einvalid_dialog_format,
     _T("ダイアログのフォーマットが不正です")),
MSG (Einvalid_dialog_font,
     _T("不正なダイアログフォントです")),
MSG (Einvalid_dialog_item,
     _T("不正なダイアログアイテムです")),
MSG (Einvalid_dialog_caption,
     _T("不正なダイアログキャプションです")),
MSG (Eunknown_dialog_option,
     _T("不正なダイアログオプションです")),
MSG (Ehiragana_and_katakana_are_both_specified,
     _T("‘:hiragana’と‘:katakana’が両方指定されています")),
MSG (Einvalid_byte_code,
     _T("バイトコードが壊れています")),
MSG (Mfile_has_already_locked,
     _T("誰かがすでに同じファイルを編集しています。\n編集を継続しますか?")),
MSG (Ekbd_macro_called_recursively,
     _T("キーボードマクロは再帰的に実行できません")),
MSG (Eline_spacing_must_0_to_30,
     _T("行間は0から30ピクセルです")),
MSG (Edde_error,
     _T("DDEでエラーが発生しました")),
MSG (Edde_timeout,
     _T("DDE要求がタイムアウトしました")),
MSG (Edde_busy,
     _T("DDEサーバーがBUSYです")),
MSG (Edde_low_memory,
     _T("サーバー先行状態です")),
MSG (Edde_no_conv,
     _T("DDE対話が確立できません")),
MSG (Edde_not_processed,
     _T("トランザクションの実行に失敗しました")),
MSG (Edde_server_died,
     _T("サーバーが終了しました")),
MSG (Edde_terminated_transaction,
     _T("終了したトランザクションです")),
MSG (Ekbd_input_is_disabled,
     _T("キーボードからの入力はできません")),
MSG (Efiler_is_not_open,
     _T("ファイラがオープンされていません")),
MSG (Efiler_is_not_in_dual_window_mode,
     _T("ファイラが2画面モードではありません")),
MSG (Einvalid_if_access_denied_option,
     _T("不正な‘:if-access-denied’オプションです")),
MSG (Eassoc_incomplete,
     _T("ファイル名の関連付けが不完全、または無効です")),
MSG (Eno_assoc,
     _T("指定されたファイル名拡張子には、アプリケーションが関連付けられていません")),
MSG (Einvalid_dictionary,
     _T("辞書が壊れています")),
MSG (ARC_ERROR_DISK_SPACE,
     _T("解凍する為のディスクの空きが足りません")),
MSG (ARC_ERROR_READ_ONLY,
     _T("解凍先のファイルはリードオンリーです")),
MSG (ARC_ERROR_USER_SKIP,
     _T("ユーザーによって解凍をスキップされました")),
MSG (ARC_ERROR_UNKNOWN_TYPE,
     _T("格納ファイルの種類が不明です")),
MSG (ARC_ERROR_METHOD,
     _T("UNZIP32.DLL で扱えない格納モードで格納されています")),
MSG (ARC_ERROR_PASSWORD_FILE,
     _T("格納ファイルにパスワードがかかっています")),
MSG (ARC_ERROR_VERSION,
     _T("格納ファイルの形式が未対応のバージョンです")),
MSG (ARC_ERROR_FILE_CRC,
     _T("格納ファイルのチェックサムが合っていません")),
MSG (ARC_ERROR_FILE_OPEN,
     _T("解凍時にファイルを開けませんでした")),
MSG (ARC_ERROR_MORE_FRESH,
     _T("より新しいファイルが解凍先に存在しています")),
MSG (ARC_ERROR_NOT_EXIST,
     _T("ファイルは解凍先に存在していません")),
MSG (ARC_ERROR_ALREADY_EXIST,
     _T("ファイルが解凍先に既に存在しています")),
MSG (ARC_ERROR_TOO_MANY_FILES,
     _T("格納ファイル数が限界を越えています")),
MSG (ARC_ERROR_DIRECTORY,
     _T("ディレクトリが作成できません")),
MSG (ARC_ERROR_CANNOT_WRITE,
     _T("解凍中に書き込みエラーが生じました")),
MSG (ARC_ERROR_HUFFMAN_CODE,
     _T("アーカイブファイルのハフマンコードが壊れています")),
MSG (ARC_ERROR_COMMENT_HEADER,
     _T("アーカイブファイルのコメントヘッダが壊れています")),
MSG (ARC_ERROR_HEADER_CRC,
     _T("アーカイブファイルのヘッダのチェックサムが合っていません")),
MSG (ARC_ERROR_HEADER_BROKEN,
     _T("アーカイバファイルのヘッダが壊れています")),
MSG (ARC_ERROR_ARC_FILE_OPEN,
     _T("アーカイブファイルを開く事が出来ません")),
MSG (ARC_ERROR_NOT_ARC_FILE,
     _T("指定したファイルは、アーカイブファイルではありません")),
MSG (ARC_ERROR_CANNOT_READ,
     _T("アーカイブファイルの読み込み時に読み込みエラーが出ました")),
MSG (ARC_ERROR_FILE_STYLE,
     _T("指定されたファイルはアーカイブファイルではありません")),
MSG (ARC_ERROR_COMMAND_NAME,
     _T("コマンド指定が間違っています")),
MSG (ARC_ERROR_MORE_HEAP_MEMORY,
     _T("作業用のためのヒープメモリが不足しています")),
MSG (ARC_ERROR_ENOUGH_MEMORY,
     _T("グローバルメモリが不足しています")),
MSG (ARC_ERROR_DEAD,
     _T("アーカイバDLLが死にました")),
MSG (Eextract_error,
     _T("解凍中にエラーが発生しました")),
MSG (Ecompress_error,
     _T("圧縮中にエラーが発生しました")),
MSG (Ecompress_not_supported,
     _T("圧縮はサポートしていません")),
MSG (Epower_number_too_large,
     _T("べきが大きすぎます")),
MSG (Ezero_denominator,
     _T("分母が0です")),
MSG (Ebignum_overflow,
     _T("整数演算がオーバーフローしました")),
MSG (Einvalid_complex_syntax,
     _T("不正な複素数の構文です")),
MSG (Evector_is_not_adjustable,
     _T("サイズ変更可能なベクタではありません")),
MSG (Eunmatch_array_type,
     _T("共有する配列の型が違います")),
MSG (Edisplaced_to_array_too_small,
     _T("共有する配列が小さすぎます")),
MSG (Earray_size_too_large,
     _T("配列のサイズが大きすぎます")),
MSG (Earray_rank_too_large,
     _T("配列のランクが大きすぎます")),
MSG (Earray_type_mismatch,
     _T("配列の型が異なります")),
MSG (Ecannot_replace_displace_array,
     _T("共有している配列は交換できません")),
MSG (Eis_not_adjustable_array,
     _T("変更可能でない配列は交換できません")),
MSG (Eis_same_array,
     _T("同一の配列は交換できません")),
MSG (Earray_rank_mismatch,
     _T("配列のランクが異なります")),
MSG (Eno_rank_is_specified,
     _T("配列のランクが指定されていません")),
MSG (Eno_initializer_for_array,
     _T("配列の初期化オブジェクトがありません")),
MSG (Earray_initializer_count_mismatch,
     _T("配列の初期化オブジェクトの個数が異なっています")),
MSG (Ecannot_coerce_to_character,
     _T("文字への変換はサポートされていません")),
MSG (Einvalid_slot,
     _T("不正なスロットです")),
MSG (Estructure_includes_recursively,
     _T("構造体が再帰的にincludeされています")),
MSG (Ewrong_slot_description,
     _T("不正なスロット記述子です")),
MSG (Eis_typed_structure,
     _T("型付きの構造体です")),
MSG (Eend_of_file,
     _T("EOFに達しました")),
MSG (Eunknown_folder_name,
     _T("未定義のフォルダ名です")),
MSG (Eunknown_STRRET_type,
     _T("未定義のSTRRETタイプです")),
MSG (Ecomma_atsign_is_not_in_backquote,
     _T("‘,@’がバッククオート構文以外に現れました")),
MSG (Ecomma_dot_is_not_in_backquote,
     _T("‘,.’がバッククオート構文以外に現れました")),
MSG (Ecomma_is_not_in_backquote,
     _T("‘,’がバッククオート構文以外に現れました")),
MSG (Eunknown_c_type,
     _T("未定義のC型指定子です")),
MSG (Einvalid_c_argument_type,
     _T("引数の型が不正です")),
MSG (Edll_not_initialized,
     _T("DLL関数は初期化されていません")),
MSG (Ewrong_function_bar_char,
     _T("指定された文字はファンクションバーに割り当てられません")),
MSG (Ebad_function_bar_label_number,
     _T("不正なファンクションバーのラベル数です")),
MSG (Einvalid_encoding_option,
     _T("不正な‘:encoding’オプションです")),
MSG (Edde_undefined_return_type,
     _T("未定義のdde-request型です")),
MSG (EPDERR_INITFAILURE,
     _T("プリンタの初期化に失敗しました")),
MSG (EPDERR_LOADDRVFAILURE,
     _T("プリンタのデバイスドライバをロードできません")),
MSG (EPDERR_NODEFAULTPRN,
     _T("通常使うプリンタが設定されていません")),
MSG (EPDERR_NODEVICES,
     _T("プリンタドライバが見つかりません")),
MSG (EPDERR_PRINTERNOTFOUND,
     _T("プリンタが正しくインストールされていません")),
MSG (Esuffix_too_long,
     _T("拡張子が長すぎます")),
MSG (Mclumsy_backup_filename,
     _T("不細工なバックアップファイル名になってしまいました")),
MSG (Einvalid_share_option,
     _T("不正な‘:share’オプションです")),
MSG (Eprefix_too_long,
     _T("プリフィックスが長すぎます")),
MSG (ARC_ERROR_NOT_SUPPORT,
     _T("アーカイバ DLL でサポートされていません")),
MSG (Ecannot_convert_to_variant,
     _T("VARIANTに変換できません")),
MSG (Einvalid_idispatch,
     _T("不正なoledataです")),
MSG (Ecannot_convert_from_variant,
     _T("未サポートのVARIANTタイプです")),
MSG (Ereadtable_value_is_not_readtable,
     _T("*readtable*の値がリードテーブルではありません")),
MSG (Emacro_char_out_of_range,
     _T("範囲外のマクロ文字です")),
MSG (Edispmacro_sub_char_out_of_range,
     _T("範囲外のディスパッチングマクロ副文字です")),
MSG (Eis_not_a_dispmacro_char,
     _T("ディスパッチングマクロ文字ではありません")),
MSG (Enumeric_dispmacro_sub_char,
     _T("ディスパッチングマクロ副文字が数値です")),
MSG (Eis_not_a_macro_char,
     _T("マクロ文字ではありません")),
MSG (Eis_not_a_dispmacro_sub_char,
     _T("ディスパッチングマクロ副文字ではありません")),
MSG (Einvalid_readtable_case,
     _T("不正なreadtable-caseです")),
MSG (Eis_special_form,
     _T("特殊形式です")),
MSG (Einvalid_window_configuration,
     _T("不正なwindow-configurationです")),
MSG (Einvalid_doc_file,
     _T("DOCファイルが壊れています")),
MSG (Ecomplex_regexp,
     _T("もちっとシンプルな正規表現にしてください")),
MSG (Etarget_xyzzy_is_busy,
     _T("なんか忙しいみたいなんで、また後にしましょう")),
MSG (Euncompress_not_supported,
     _T("解凍はサポートしていません")),
MSG (Eunknown_charset,
     _T("不明な文字セットです")),
MSG (Eunsupported_charset,
     _T("未サポートの文字セットです")),
MSG (Eunsupported_codepage,
     _T("未サポートのコードページです")),
MSG (Eunknown_char_encoding,
     _T("不明なエンコードです")),
MSG (Enot_a_shortcut,
     _T("ショートカットではありません")),
MSG (Etimezone_is_integral_multiple_of_1_3600,
     _T("タイムゾーンは1/3600の整数倍です")),
MSG (Eremove_not_supported,
     _T("削除はサポートしていません")),
MSG (Eremove_error,
     _T("削除中にエラーが発生しました")),
MSG (Ecannot_open_bmp_file,
     _T("ファイルがオープンできません")),
MSG (Ebad_bmp_format,
     _T("認識できないビットマップファイルです")),
MSG (Eunsupported_bmp_format,
     _T("未サポートのビットマップファイル形式です")),
MSG (Ecannot_create_bitmap,
     _T("ビットマップが作成できません")),
MSG (ECannot_create_toolbar,
     _T("ツールバーが作成できません")),
MSG (Etoo_many_tool_items,
     _T("ツールボタンが多すぎます")),
MSG (Eno_tool_items,
     _T("ツールボタンが指定されていません")),
MSG (Etoolbar_exist,
     _T("ツールバーはすでに存在します")),
MSG (Eundefined_toolbar,
     _T("未定義のツールバーです")),
MSG (Enot_a_tab_bar,
     _T("タブバーではありません")),
MSG (Emultiple_position_specified,
     _T("タブの位置指定が不正です")),
MSG (Eno_event_sink,
     _T("EventSinkが定義されていません")),
MSG (Etab_not_found,
     _T("指定されたタブが見つかりません")),
MSG (Erename_failed,
     _T("すまんす。\n\n%s\nを\n%s\nにリネームできません。自力で何とかしてください。")),
MSG (ESHFileOperation_not_supported,
     _T("SHFileOperationはサポートされていません")),
MSG (Edelete_failed,
     _T("削除できません")),
MSG (Enot_in_gzip_format,
     _T("gzipフォーマットではありません")),
MSG (Egzip_data_error,
     _T("gzip data error")),
MSG (Eregexp_too_long,
     _T("正規表現が長すぎます")),
MSG (Ehtml_help_does_not_supported,
     _T("HtmlHelpはサポートされていません")),
MSG (Ehtml_help_error,
     _T("HtmlHelp")),
MSG (Einvalid_ienum_variant,
     _T("不正なoledataです")),
