#include "cdecl.h"
#include "version.h"

#if !PROGRAM_PATCH_LEVEL
# if !PROGRAM_MINOR_REVISION
#  if !PROGRAM_MAJOR_REVISION
#   define PROGRAM_VERSION \
  _TOTSTR (PROGRAM_MAJOR_VERSION) _T(".") _TOTSTR (PROGRAM_MINOR_VERSION)
#  else /* PROGRAM_MAJOR_REVISION */
#   define PROGRAM_VERSION \
  _TOTSTR (PROGRAM_MAJOR_VERSION) _T(".") _TOTSTR (PROGRAM_MINOR_VERSION) \
    _T(".") _TOTSTR (PROGRAM_MAJOR_REVISION)
#  endif /* PROGRAM_MAJOR_REVISION */
# else /* PROGRAM_MINOR_REVISION */
#  define PROGRAM_VERSION \
  _TOTSTR (PROGRAM_MAJOR_VERSION) _T(".") _TOTSTR (PROGRAM_MINOR_VERSION) \
    _T(".") _TOTSTR (PROGRAM_MAJOR_REVISION) _T(".") _TOTSTR (PROGRAM_MINOR_REVISION)
# endif /* PROGRAM_MINOR_REVISION */
#else /* PROGRAM_PATCH_LEVEL */
#  define PROGRAM_VERSION \
  _TOTSTR (PROGRAM_MAJOR_VERSION) _T(".") _TOTSTR (PROGRAM_MINOR_VERSION) \
    _T(".") _TOTSTR (PROGRAM_MAJOR_REVISION) _T(".") _TOTSTR (PROGRAM_MINOR_REVISION) \
      _T(".") _TOTSTR (PROGRAM_PATCH_LEVEL)
#endif /* PROGRAM_PATCH_LEVEL */

#if (PROGRAM_MAJOR_VERSION == 0 && PROGRAM_MINOR_VERSION == 2 \
     && PROGRAM_MAJOR_REVISION == 1 && PROGRAM_MINOR_REVISION == 176)
# define DISPLAY_VERSION_STRING _T("0.2.1.0xB0") // ”±‚ç‚µ‚¢
#else
# define DISPLAY_VERSION_STRING PROGRAM_VERSION
#endif

#define TITLEBAR_STRING _T(PROGRAM_NAME) _T(" ") DISPLAY_VERSION_STRING

TCHAR TitleBarString[TITLE_BAR_STRING_SIZE] = TITLEBAR_STRING;
const TCHAR VersionString[] = PROGRAM_VERSION;
const TCHAR DisplayVersionString[] = DISPLAY_VERSION_STRING;
const TCHAR ProgramName[] = _T(PROGRAM_NAME);
const TCHAR ProgramNameWithVersion[] = _T(PROGRAM_NAME) _T(" version ") PROGRAM_VERSION;
